Install smbclient when setting up arch smb
Leaving out smbclient from the install will cause a cyclical
dependency error.

```
Was getting error
Stderr from the command:

warning: dependency cycle detected:
warning: smbclient will be installed before its cifs-utils dependency
error: failed to commit transaction (conflicting files)
```